[package]
name = "treeup"
license = "MIT or Apache-2.0"
authors = ["Taxrosdev"]
version = "0.1.0"
edition = "2024"

[dev-dependencies]
temp-dir = "0.2.0"
tokio = { version = "1.0", features = ["macros"] }

[dependencies]
blake3 = "1.8.6"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
snafu = "0.9.2"
tokio = "1.0"
